### ISSUE TITLE
Linkdrop-Webapp documentation v1

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/Linkdrop-Webapp#3]
## Requirements

- [x] Review needed updates to current eth2 documentation 
- [x] Implement edits to finalize the Web-app documentation text
- [x] Implement text in https://www.gitbook.com/ account
- [ ] Link "Docs" tab on linkdrop website & github linking to the documentation mainpage

**Comment by Kisgus** [comment]
Please review: https://linkdrop.gitbook.io/docs/

**Comment by artignatev** [comment]
@Dobrokhvalov do we need to update scheme images?

**Comment by Kisgus** [comment]
Could you please link the "Docs" tab on the linkdrop.org website @artignatyev ?

**Comment by Kisgus** [comment]
Outdated
